SET(UV_NAME "libuv.a")
SET(UV_SOURCE_DIR ${PROJECT_SOURCE_DIR}/lib/uv)
SET(UV_BUILD_DIR ${UV_SOURCE_DIR}/out)
SET(UV_BINARY_DIR ${UV_BUILD_DIR}/Debug)
SET(UV_BINARY_DST_DIR ${CMAKE_BINARY_DIR})

MESSAGE(STATUS "Start to build libuv for Android under ${UV_SOURCE_DIR}")

MESSAGE(STATUS "(1/2) Build")
EXECUTE_PROCESS(
    WORKING_DIRECTORY ${UV_SOURCE_DIR}
    COMMAND ./android-build ${ANDROID_NDK_HOME}
    OUTPUT_QUIET
)

MESSAGE(STATUS "(2/2) Copy ${UV_NAME} FROM ${UV_BINARY_DIR} TO ${UV_BINARY_DST_DIR}")
EXECUTE_PROCESS(
    WORKING_DIRECTORY ${UV_SOURCE_DIR}
    COMMAND cp ${UV_BINARY_DIR}/${UV_NAME} ${UV_BINARY_DST_DIR}/${UV_NAME}
    OUTPUT_QUIET
)

MESSAGE(STATUS "Build libuv successfully")

SET(UV_LIB "${UV_BINARY_DST_DIR}/${UV_NAME}")
